# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main£¨1£©.o
LINKOBJ  = main£¨1£©.o
LIBS     = -L"F:/SoftWare/VC++/Setup/Dev-Cpp/MinGW64/lib" -L"F:/SoftWare/VC++/Setup/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"F:/SoftWare/VC++/Setup/Dev-Cpp/MinGW64/include" -I"F:/SoftWare/VC++/Setup/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"F:/SoftWare/VC++/Setup/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"F:/SoftWare/VC++/Setup/Dev-Cpp/MinGW64/include" -I"F:/SoftWare/VC++/Setup/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"F:/SoftWare/VC++/Setup/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"F:/SoftWare/VC++/Setup/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main£¨1£©.o: main£¨1£©.c
	$(CC) -c main£¨1£©.c -o main£¨1£©.o $(CFLAGS)
